In [4]:
#global vs local

value=100
globals() #실행시키면 딕셔너리 형태로 들어있는거 보임
globals()['value'] #딕셔너리 형태 키값 인자로들어감

100

In [8]:
def func(x,y):
    return x,y
print(globals()["func"]) 

print(globals()["func"](3,5)) # 함수 실행시켜보기. 결과값 볼수 있다. 

<function func at 0x00000200C004E798>
(3, 5)


In [14]:
class Book :
    def __init__(self,name):
        self.name=name
print(globals()["Book"]) #클래스인거 알수 있음. 
print(globals()["Book"]('철저입문'))
python=globals()["Book"]('철저입문')
python.__dict__

<class '__main__.Book'>


{'name': '철저입문'}

In [17]:
names=['kang','hong','kim']

print(names)
print(len(names))
print(names[2])

student_names=names
student_names[2]='lee'
print(names)   # 나는 student_names만 바꿨는데 실제로 출력하면 names도 같이 바뀌었음.(주의)************
## 주소를 복사해서 넘긴것


['kang', 'hong', 'kim']
3
kim
['kang', 'hong', 'lee']


In [18]:
a=10 
b=a
b=20
print(a,b) #얘는 값을 복사해서 넘기고 

10 20


In [23]:
def my_fun(a):
    a=a+10
    print(a)
    
my_fun(a)
print(a) # a는 그대로 10이다. 주소를 복사한게 아니라 값을 복사한것이다.  call by value


a=[10]
def my_fun(a):
    a[0]=a[0]+10
    print(a)
    
my_fun(a)
print(a) ## 얘는 아얘 값이 바뀌어짐. call by reference ,인자를 보낼때 주소값을 복사해서 전달을해준다.

[20]
[20]


In [ ]:
a=[1,2,3]


In [26]:
arrays=[[1,2,3],[4,5,6],[7,8,9]]
arrays[0]



<class 'list'>


In [31]:
lista=[[10,20],[30,40],[50,60]]
listb=lista

listb[0][0]=500
print(lista)
print(listb)
print(id(lista))
print(id(listb))

[[500, 20], [30, 40], [50, 60]]
[[500, 20], [30, 40], [50, 60]]
2202251702856
2202251702856


In [30]:
import copy #이 모듈을 사용해서 리스트 복사를 하자 그래야 그안에 있는 것도 새로만들어서 복사한다.

listb=copy.deepcopy(lista)
listb[0][1]=1000

print(lista)
print(listb)
print(id(lista))
print(id(listb))

[[500, 20], [30, 40], [50, 60]]
[[500, 1000], [30, 40], [50, 60]]
2202151957896
2202240293896


## NUMPY 
-배열을 쓸수 있게 만든다. 과학 연산을 쉼고 빠르게 할수 있는 패키지
-배열이랑 리스트랑은 다르다. 
-속도가 엄청 빨라서 사용함(주이유)

In [32]:
import numpy  as np  # C언어로 구현돼서 빠르다.


In [38]:
#시퀀스 데이터를 이용한 배열(ndarray) 생성

data1=[1,2,3,4,5,6]
arr1=np.array(data1) #배열을 만드는것
print(type(arr1))
arr1

#차원이 다른애들
data2=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array(data2)
arr2 # 2차원 배열로 출력됨

data3=[1.2,3.4,5.6,4.4,4.5]
arr3=np.array(data3)
arr1.dtype  #배열안에 들어 있는 데이터 타입이 뭔지?!
arr3.dtype

<class 'numpy.ndarray'>


dtype('float64')

In [40]:
data4=[1.,2.,3.,40]  # 정수 실수를 섞어서 쓰니까 dtype 은 실수다.
arr4=np.array(data4)
arr4.dtype 

dtype('float64')

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(1,20) #시작값주기 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [45]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [46]:
np.arange(1,10,2,dtype='float') # 실수로도 지정할수 있다. 

array([1., 3., 5., 7., 9.])

In [49]:
arr5=np.arange(10).reshape(2,5)  #(주의) 원소 총 개수가 행*열과 맞아야 한다.
print(arr5)
arr5.shape #몇행 몇열인줄 볼수있다.

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [48]:
arr1.shape

(6,)

In [1]:
np.ones((3,4)) #값을 1로 전부 채우겠다는 의미.


np.ones((3,5,2)) #3차원으로 한다. 

np.empty((3,4))

NameError: name 'np' is not defined

In [55]:
np.full((3,5),7) # 3핵 5열 함수를 7로 채운다.

np.eye(3) #단위 행렬 만들기 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.linspace(1,10,3) # 균등하게 나누는것.

array([ 1. ,  5.5, 10. ])

In [65]:
data6=['1','2','3']  # 문자열로 들어감 이걸 정수로 변환해줄수 있다. 
arr6=np.array(data6)
print(data6)
arr6

arr6_num=arr6.astype(int)
arr6_num.dtype
print(arr6_num)
print(arr6)

['1', '2', '3']
[1 2 3]
['1' '2' '3']


In [62]:
arr6.dtype


dtype('<U1')

In [67]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [72]:
#random을 이용해서 값을 채워줌.
#1. rand 이용 :0~1사이의 값으로 adarray를 생성한다.(0포함,1불포함)

print(np.random.rand())

print(np.random.rand(4,3,2)) #4차원 3행 2열
print("---------------")
print(np.random.rand(3,2)) #3행 2열

0.025545430616634945
[[[0.33966115 0.71884512]
  [0.86817495 0.21146037]
  [0.22876074 0.27194887]]

 [[0.55955532 0.39330407]
  [0.34410796 0.38857483]
  [0.83696601 0.95524852]]

 [[0.98930392 0.32125886]
  [0.32391672 0.42975388]
  [0.10840225 0.14542459]]

 [[0.74167044 0.09780899]
  [0.08466071 0.35862511]
  [0.89222252 0.43029934]]]
---------------
[[0.73450676 0.44438305]
 [0.8569413  0.47662443]
 [0.38958397 0.20805452]]


In [94]:
print(np.random.randn(4)) 

#특정 정수 사이에서 랜덤한 값으로 ndarray생성
print(np.random.randint(10)) 
print(np.random.randint(1,100,size=(3,5)))  #사이즈로 행렬 표시함.  #배열 만들려면 반드시 사이즈를 줘야한다. 
print(np.random.randint(90,100,size=(5))) 


#seed -랜덤한 값을 동일하게 다시 생성하고자 할때..

np.random.seed(23) #이안에 숫자는 크게 의미가 있진 않음,..아무 숫자나 넣어야 한다.
#같은 seed를 가지고랜덤하게 만들고
np.random.randn(3,4)  #이거 여러번 실행해도 아까랑 같은 값을 계속 출력해준다. seed값 때문에.

[ 0.32227152  0.06034293 -1.04345    -1.00994188]
4
[[44 16 87 84 59]
 [26 67 75 36 97]
 [57 14 61 23 39]]
[90 95 96 90 92]


array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

In [96]:
np.random.rand(2,3)
np.random.rand(2,3,6)

array([[[0.42159653, 0.34648944, 0.86978508, 0.42860181, 0.82875148,
         0.71785184],
        [0.11922669, 0.59638417, 0.1297563 , 0.07753409, 0.83120526,
         0.46438561],
        [0.16201248, 0.54797529, 0.58848582, 0.77361317, 0.65584546,
         0.55770676]],

       [[0.17824727, 0.24058353, 0.50605463, 0.3967457 , 0.48305519,
         0.95573984],
        [0.90160219, 0.50575932, 0.82070149, 0.82771593, 0.23183335,
         0.07905549],
        [0.46576293, 0.87897581, 0.14750306, 0.23125131, 0.91794581,
         0.12906353]]])

In [101]:
#choice 주어진 1차원 ndarray로 부터 랜덤으로 샘플링함.

sample_data=np.array([10,20,30,40,50])
np.random.choice(sample_data,size=(2,3))

print("-----------------------------")
#choice -정수가 주어지면 np.arrange(정수)으로 간주함. 
np.random.choice(100,size=(4,5)) #한번 뽑은 값을 또 써도 괜찮다 중복된 값이 나올수 있다.

np.random.choice(100,size=(4,5),replace=False)#중복된 값을 가지지 못하게 한다.

-----------------------------


array([[35, 25, 42, 81, 30],
       [52,  0,  9, 41, 29],
       [96, 24,  4,  2, 84],
       [ 1, 41, 99, 54, 77]])

In [143]:
np.random.choice(np.arange(1,46),size=6,replace=False) #로또 뽑기

# np.random.choice([1,2,3,4,5,6],size=6,replace=False) 

array([13, 31,  9, 24, 35, 28])

In [111]:
np.random.normal(size=(3,4))

array([[ 1.0654228 , -0.6055636 , -1.33355413,  0.49605774],
       [ 0.01319381, -0.48521005,  0.11583088,  0.66509522],
       [-0.0265563 ,  0.62321928, -0.00374142,  0.27196926]])

In [121]:
#배열의 연산

arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
arr1+arr2


arr3=np.arange(15).reshape(3,5)
print(arr3)

arr4=np.arange(15).reshape(3,5)

arr3+arr4


np.add(arr3,arr4)

arr3*arr4


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [148]:
ar1=np.array([1,2,3,4,5])
ar2=np.array([6,7,8,9,10])

ar1**ar2

print(ar1**2)

ar1>10

[ 1  4  9 16 25]


array([False, False, False, False, False])

In [159]:
#통계 함수 =평균 분산 최대 최소 
print(arr1)

np.mean(arr1)
arr1.mean() # 둘다 평균을 이용할수 있는 방법. 

print(arr1.std())

np.cumsum(arr1)  # 누적해서 값을 구해준다.

np.cumprod(arr1) #누적곱

arr5>0 #양수 트로 음수 펄스



[10 20 30 40]
11.180339887498949


array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [161]:
#any,all 함수
# any =특정 조건을 만족하는 것이 하나라도 존재하면 True,아니면 Flase
# all=모든 원소가 특정 조건에 만족해야만 true, 아니면 false

np.any(arr5>0)
np.all(arr5>0)

False

In [162]:
# where 함수
# 조건에 따라서 선별적으로 값을 선택

np.where(arr5>0,arr5,0) #true 면 arr5 반환 아니면 flase 면 0반환

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 인덱싱 : 했을때는 차원이 하나 준다. 슬라이싱은 줄지 않음
-파이썬의 리스트와 동일한 개념으로 사용한다.
-1차원 벡터 인덱싱


In [164]:
arr1[3]

arr1[3]=1000
print(arr1)

[  10   20   30 1000]


In [177]:
#2차원 행렬인덱싱

arr2=np.arange(10).reshape(2,5)
arr2

#원소에 접근하기 : 인덱스를 ,로 구분해서 접근한다. 
print(arr2[1,2])

ar3=np.random.randint(1,50,size=(3,4,5))
print(ar3)
print(ar3[1,2,2])

#인덱스를 이용한 값 변경

ar3[1,2,2]=10000
print(ar3)

ar3[0]=np.zeros((4,5))
print(ar3)

7
[[[23 26 24 11 38]
  [ 2 30 11 13 30]
  [27 38 18 25 15]
  [23  2  7 31 31]]

 [[ 2 23 39 44 37]
  [19 43 37  2 22]
  [35 10  4 42 34]
  [44 29  3 16 16]]

 [[20 38 31 29  9]
  [20  7 47 29 20]
  [42 29 25 31 15]
  [ 2 21 31 37 21]]]
4
[[[   23    26    24    11    38]
  [    2    30    11    13    30]
  [   27    38    18    25    15]
  [   23     2     7    31    31]]

 [[    2    23    39    44    37]
  [   19    43    37     2    22]
  [   35    10 10000    42    34]
  [   44    29     3    16    16]]

 [[   20    38    31    29     9]
  [   20     7    47    29    20]
  [   42    29    25    31    15]
  [    2    21    31    37    21]]]
[[[    0     0     0     0     0]
  [    0     0     0     0     0]
  [    0     0     0     0     0]
  [    0     0     0     0     0]]

 [[    2    23    39    44    37]
  [   19    43    37     2    22]
  [   35    10 10000    42    34]
  [   44    29     3    16    16]]

 [[   20    38    31    29     9]
  [   20     7    47    29    20]
  [ 

In [183]:
arr6=np.array([1,2,3,4,5,6])
arr6[arr6>3] #조건에 맞는 배열만 출력하기 

#슬라이싱
arr7=np.arange(10)
print(arr7)
print(arr7[2:-3])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]


In [228]:
#2차원 배열 슬라이싱
arr8=np.arange(10).reshape(2,5)
print (arr8)
print("------------")
print(arr8[:][1:])
print("==============")
b2=np.arange(10,100,10).reshape(3,3)
print(b2)
print()
print(b2[:,1:])
print("@@@@@@@@@@")
print(b2[1:][0:])

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------
[[5 6 7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[20 30]
 [50 60]
 [80 90]]
@@@@@@@@@@
[[40 50 60]
 [70 80 90]]


In [198]:
#ndarray의 shpae 변경방법...
arr11=np.arange(15).reshape(3,5)
print(arr11)

print(np.ravel(arr11))  # 행을 기준으로 일자로 펼치기
print(np.ravel(arr11,order='F')) # 열기준으로 펼치기 

print()
arr12=np.arange(36).reshape(3,4,3)
print(arr12)

ar12=np.ravel(arr12)
ar12[0]=-12
print(arr12)   #원래 값이 바뀐다 . ravel은 그냥 가져다 쓰는거임.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[[[-12   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]]

 [[ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]]

 [[ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]]]


In [203]:
#flatten사용하면 값을 따로 해서 바꿀수 있다.

ar13=arr12.flatten()  #매번 새로운 애를 생성해준다. 
ar13[0]=-123
ar13
arr12



array([[[-12,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23]],

       [[ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35]]])

In [217]:
#axis

a = np.arange(15)
print(np.sum(a))

# print(np.sum(a, axis=1)) # 중심축을 이야기한다. 1차원에서는 0이다 없는거라고 보면된다. axis 안들어 가면 기본적으로 전체를 의미한다.

b=np.arange(15).reshape(3,5)
print(b)
print()
print(np.sum(b))
print()
print(np.sum(b,axis =0)) # 열이 기준이 된다.
print()
print(np.sum(b,axis =1)) #행을 기준으로 연산이 된다.


105
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

105

[15 18 21 24 27]

[10 35 60]


In [224]:
c=np.arange(48).reshape(3,4,4)
print(c)
print(np.sum(c,axis=0)) #각 위치 원소기준
print()
print(np.sum(c,axis=1)) #열기준
print()
print(np.sum(c,axis=2)) #향기준

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
[[48 51 54 57]
 [60 63 66 69]
 [72 75 78 81]
 [84 87 90 93]]

[[ 24  28  32  36]
 [ 88  92  96 100]
 [152 156 160 164]]

[[  6  22  38  54]
 [ 70  86 102 118]
 [134 150 166 182]]


In [ ]:
#행렬 브로드 캐스팅 broadingcasting :두개의 행랼연산 shape이 다른애들끼리하는것 .1.4*4,3 가운데 두개가 맞아야 할수 있다. 
