## NumPy 실습문제

1. 0으로 채워진 크기가 20인 배열을 생성하세요. 

In [3]:
import numpy as np

np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

2. 0부터 15까지의 값을 갖는 4 x 4 행렬을 생성하세요. 

In [5]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

3. 길이가 10인데 세번째 요소만 1이고, 나머지 요소는 0인 배열을 생성하세요.

In [6]:
arr1=np.zeros(10)
arr1[2]=1
arr1

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

4. 1에서 10까지의 값을 갖는 배열을 생성하세요.

In [15]:
# np.random.choice(np.arange(1,11),size=10,replace=False)
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

5. 위의 배열의 순서를 거꾸로 바꿔주세요. 

In [16]:
a=a[::-1]
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

6. 4x4 단위행렬을 만드세요. (단위 행렬(영어: identity matrix)은 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다.)

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. 랜덤한 값을 가지는 3X3X3 배열을 생성하세요. 

In [24]:
arr2=np.random.rand(3,3,3)
print(arr2)

[[[0.98427201 0.50063591 0.73711995]
  [0.46970078 0.59812189 0.50480081]
  [0.30298268 0.1661266  0.5403556 ]]

 [[0.92044326 0.69046459 0.20657487]
  [0.16466411 0.12699923 0.42272628]
  [0.15979931 0.43839405 0.57031036]]

 [[0.53481495 0.60396861 0.78228808]
  [0.58110241 0.67609306 0.5260151 ]
  [0.08173744 0.9436227  0.18303112]]]


8. 위에서 생성한 배열 원소의 최대값, 최솟값을 구하세요. 

In [26]:
print(arr2.max())
print(np.min(arr2))

0.9842720147065838
0.08173744305849318


9. 20개의 랜덤한 값을 가진 배열을 생성하고, 그 배열의 평균값을 구하시오.  
    참고: numpy에서 평균을 구하는 함수 - mean() 

In [29]:
arr3=np.random.randint(50,size=20)
print(np.mean(arr3))

29.1


10. 4x4 의 2차원 배열을 생성하세요. 단 테두리는 1을 내부는 0으로 채워주세요. 

In [40]:
arr4=np.ones((2,4,4))
arr4[:,1:3,1:3]=0

arr4

array([[[1., 1., 1., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.]]])